services:
  evatorrent:
    image: akashkece/evatorrent:0.2.0
    container_name: evatorrent
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./downloads:/downloads
    environment:
      - PYTHONUNBUFFERED=1
